From python:3
Add basic_1.py /

RUN pip3 install --user vincent plotly pandas matplotlib tabulate mpl_toolkits folium ipywidgets
RUN jupyter nbextension --py enable widgetsnbextension

CMD [ "python3", "./basic_1.py" ]
